# Generated by Django 3.2.9 on 2024-07-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelike',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='recipe.recipe'),
        ),
    ]
