# Generated by Django 3.2.9 on 2024-07-29 14:00

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipelike_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=recipe.models.get_default_recipe_category, on_delete=models.SET(recipe.models.get_default_recipe_category), related_name='recipe_list', to='recipe.recipecategory'),
        ),
    ]
